### ISSUE TITLE
Trying to use Linebreak in config.yml

### ISSUE THREAD

**Issue by TheDesignCraftYT** [C1200/BungeeMOTD#1]
Hey!
I'm trying to use a linebreak in the config.yml but its not working.

![grafik](https://user-images.githubusercontent.com/84375152/155976814-77b11428-2bef-4c94-bf8c-005f8eea64fa.png)

![grafik](https://user-images.githubusercontent.com/84375152/155976834-a49403ff-6d63-4d65-b18f-e63dacbcb3cb.png)

**Comment by C1200** [comment]
Hello! Please could you send over your config file so I can see what the problem could be.

**Comment by TheDesignCraftYT** [comment]
Sure. 
```yml
Prefix: '&l&bTheDesignCraft &3MC &r&8● &7'
Maintenance:
  enable: false
  Layout:
    FirstLine: ' &bTheDesignCraft &3MC &7| &eCitybuild Netzwerk &f[&61.8.x&7-&61.18.x&f]'
    SecondLine: '             &8* &cWir sind in Wartung! &8*'
  Protocol: '&8-> &cWartungsmodus'
  Message: "&8-------------------- \n &cDer Server ist in Wartung \n &e \n &cBitte\
    \ versuche es spaeter erneut \n &8--------------------"
  PlayerInfo: "&bmc&8.&3thedesigncraft&8.&ade &7● &cWartung \n&7Discord &8» &eSoon\
    \ \n&7Release &8» &cKein feststehendes Datum"
Whitelist: []
MOTD:
  Layout:
    FirstLine: ' &bTheDesignCraft &3MC &7| &eCitybuild Netzwerk &f[&61.8.x&7-&61.18.x&f]'
    SecondLine: '            &bJETZT NEU!! &8-> &eKreativ CB'
  PlayerInfo: "&bmc&8.&3thedesigncraft&8.&ade &7-> &eServer Netzwerk \n&7Discord &8» &eSoon"
```
